version: "3.7"

services:
  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: database
      MYSQL_USER: admin
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
volumes:
  mysql_data:
            